# Image source
FROM nhenrot/obj_detect_api_base:latest

# Set work directory
WORKDIR /app

# Add application
COPY . /app

# Add docker-compose-wait tool so as to be able to wait for databases to be up

ENV WAIT_VERSION 2.7.2
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/$WAIT_VERSION/wait /wait
RUN chmod +x /wait

# Startup API
# CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000",  "--reload"]
#  Specified in docker-compose.yaml  port depends on instance (fo:8000/bo:8001)